# Generated by Django 6.0 on 2025-12-04 21:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Наименование организации')),
                ('type', models.CharField(max_length=100, verbose_name='Тип организации')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('website', models.CharField(blank=True, max_length=150, null=True, verbose_name='Веб-сайт')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('permissions', models.TextField(blank=True, null=True, verbose_name='Описание прав доступа')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainvip.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VIPClient',
            fields=[
                ('vip_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронная почта')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('potential', 'Потенциальный'), ('archived', 'Архивный')], default='active', max_length=50, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainvip.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'VIP-клиент',
                'verbose_name_plural': 'VIP-клиенты',
                'db_table': 'vip_clients',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата взаимодействия')),
                ('type', models.CharField(choices=[('meeting', 'Встреча'), ('email', 'Письмо'), ('call', 'Звонок'), ('project', 'Участие в проекте'), ('agreement', 'Согласование'), ('other', 'Другое')], max_length=50, verbose_name='Тип взаимодействия')),
                ('channel', models.CharField(blank=True, choices=[('phone', 'Телефон'), ('email', 'Email'), ('in_person', 'Личная встреча'), ('online', 'Онлайн'), ('other', 'Другое')], max_length=50, null=True, verbose_name='Канал связи')),
                ('description', models.TextField(verbose_name='Подробности взаимодействия')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vip_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainvip.vipclient', verbose_name='VIP-клиент')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'db_table': 'interactions',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
